#!/bin/sh
NPM_GLOBAL=`npm root -g`;
GLOBAL="$NPM_GLOBAL/messagelint/bin/commit-msg"

if [ ! -f "$GLOBAL" ]; then
  echo "Error: Couldn't find MessageLint, are you sure it is set up correctly?"
  exit -1
fi

MESSAGE=`cat $1`
OUTPUT=`eval "$GLOBAL '$MESSAGE' $@"` && echo $OUTPUT > $1
